Repository swyp3-babpool/babpool-frontend, pull requests merged in 2024-03, with the labels that each got.

#26 알림페이지 각 상태별로 분기하여 ui 수정
  src/assets/icons/ic_profile_default.png
  src/assets/icons/ic_profile_default_purple.png
  src/assets/styles/theme.ts
  src/components/common/button/index.tsx
  src/components/common/header/index.tsx
  src/components/common/popup/index.tsx
  src/components/notification/NotificationCard.tsx
  src/pages/Notification/NotificationDetailPage.styles.tsx
  src/pages/Notification/NotificationDetailPage.tsx
  src/pages/Notification/NotificationPage.styles.tsx
  src/pages/Notification/NotificationPage.tsx
Labels: 🛠 Feature, 💻 FrontEnd

#28 github: Add cicd workflow and pr template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/front-actions-flow.yaml
Labels: ✏️ Documentation, 🔗 Chore, 💻 FrontEnd

#29 밥약 요청페이지, 로그인 로직 수정
  package.json
  src/api/api.ts
  src/assets/icons/ic_radio.svg
  src/components/babpoolRequest/SelectScheduleModal.tsx
  src/components/babpoolRequest/SelectTimeBox.tsx
  src/components/common/button/index.tsx
  src/components/common/calendar/ScheduleCalendar.tsx
  src/components/common/divider/index.tsx
  src/components/common/schedule/ScheduleBox.tsx
  src/components/common/textarea/Textarea.tsx
  src/components/signup/DivisionGroup.tsx
  src/pages/babRequest/BabRequestPage.tsx
  src/pages/kakaoAuthentication/index.tsx
  src/pages/profileDetails/ProfileDetailsPage.tsx
  src/pages/signin/SignInPage.tsx
  src/routes/index.tsx
  yarn.lock
Labels: 🛠 Feature, 💻 FrontEnd

#32 Calendar type 지정 에러
  src/components/babpoolRequest/SelectScheduleModal.tsx
  src/components/common/calendar/ScheduleCalendar.tsx
  src/hooks/useNavigation.ts
Labels: 🚨 Bug

#33 github(workflow): Update cicd workflow to create env file in repo
  .github/workflows/front-actions-flow.yaml
Labels: 🔗 Chore, 💻 FrontEnd

#34 카카오 로그인 로직 수정
  src/pages/kakaoAuthentication/index.tsx
Labels: 🚨 Bug, 💻 FrontEnd

#37 마이페이지 및 프로필 카드 수정 페이지 ui 구현
  .github/ISSUE_TEMPLATE/babpool_issue_template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/front-actions-flow.yaml
  src/assets/icons/ic_active_check.svg
  src/assets/icons/ic_check.svg
  src/assets/icons/ic_close.svg
  src/assets/icons/ic_complete.svg
  src/assets/icons/ic_down_arrow.svg
  src/assets/icons/ic_modify.svg
  src/assets/icons/ic_modify_img.svg
  src/assets/icons/ic_next.svg
  src/assets/icons/ic_plus.svg
  src/assets/icons/ic_prev.svg
  src/assets/icons/ic_right_chevron.svg
  src/assets/icons/ic_select.svg
  src/assets/styles/theme.ts
  src/components/babpoolRequest/SelectScheduleModal.tsx
  src/components/common/calendar/PossibleTimeCalendar.tsx
  src/components/common/calendar/ScheduleCalendar.tsx
  src/components/common/flex/Flex.tsx
  src/components/common/keyword/KeywordList.tsx
  src/components/common/review/ReviewCount.tsx
  src/components/common/select/SelectInput.tsx
  src/components/home/HomeHeader.tsx
  src/components/home/HomeSection.tsx
  src/components/modifyProfile/SelectPossibleTimeModal.tsx
  src/components/profile/ProfileBox.tsx
  src/components/profile/ProfileKeywords.tsx
  src/components/signup/KeywordGroup.tsx
  src/components/totalBabpool/FilterModal.tsx
  src/hooks/useNavigation.ts
  src/pages/Notification/AcceptPage.styles.tsx
  src/pages/Notification/AcceptPage.tsx
  src/pages/Notification/NotificationDetailPage.styles.tsx
  src/pages/Notification/NotificationDetailPage.tsx
  src/pages/Notification/NotificationPage.tsx
  src/pages/Notification/RejectPage.styles.tsx
  src/pages/Notification/RejectPage.tsx
  src/pages/kakaoAuthentication/index.tsx
  src/pages/mypage/ModifyProfileCardPage.styles.tsx
  src/pages/mypage/ModifyProfileCardPage.tsx
  src/pages/mypage/Mypage.styles.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/profileDetails/ProfileDetailsPage.tsx
  src/routes/index.tsx
Labels: 🛠 Feature, 💻 FrontEnd

#38 로그인 후 엑세스 토큰 저장, axios interseptor구현
  package.json
  src/api/api.ts
  src/api/auth/auth.ts
  src/api/profile/profileApi.ts
  src/assets/banner/banner2.png
  src/assets/icons/ic_left.svg
  src/assets/icons/ic_right.svg
  src/assets/icons/ic_right_arrow.svg
  src/components/common/review/ReviewCount.tsx
  src/components/home/HomeMenu.tsx
  src/components/home/HomeSection.tsx
  src/components/signup/DivisionGroup.tsx
  src/components/signup/KeywordGroup.tsx
  src/components/totalBabpool/FilterModal.tsx
  src/components/totalBabpool/PageNation.tsx
  src/interface/api/authType.ts
  src/interface/api/commonType.ts
  src/interface/api/profileDetailsType.ts
  src/interface/api/profileType.ts
  src/main.tsx
  src/pages/home/HomePage.tsx
  src/pages/kakaoAuthentication/index.tsx
  src/pages/profileDetails/ProfileDetailsPage.tsx
  src/pages/receivedReview/ReceivedReviewPage.tsx
  src/pages/signup/SignUpPage.tsx
  src/pages/totalBabpool/TotalBabpoolPage.tsx
  src/provider/QueryProvider.tsx
  src/routes/index.tsx
  src/utils/util.ts
  yarn.lock
Labels: 🛠 Feature, 💻 FrontEnd

#39 main 브랜치에 변경사항 통합
  package.json
  src/api/api.ts
  src/api/auth/auth.ts
  src/api/profile/profileApi.ts
  src/assets/banner/banner2.png
  src/assets/icons/ic_active_check.svg
  src/assets/icons/ic_check.svg
  src/assets/icons/ic_close.svg
  src/assets/icons/ic_down_arrow.svg
  src/assets/icons/ic_left.svg
  src/assets/icons/ic_modify.svg
  src/assets/icons/ic_modify_img.svg
  src/assets/icons/ic_next.svg
  src/assets/icons/ic_plus.svg
  src/assets/icons/ic_prev.svg
  src/assets/icons/ic_right.svg
  src/assets/icons/ic_right_arrow.svg
  src/assets/icons/ic_right_chevron.svg
  src/assets/icons/ic_select.svg
  src/assets/styles/theme.ts
  src/components/babpoolRequest/SelectScheduleModal.tsx
  src/components/common/calendar/PossibleTimeCalendar.tsx
  src/components/common/keyword/KeywordList.tsx
  src/components/common/review/ReviewCount.tsx
  src/components/common/select/SelectInput.tsx
  src/components/home/HomeHeader.tsx
  src/components/home/HomeMenu.tsx
  src/components/home/HomeSection.tsx
  src/components/modifyProfile/SelectPossibleTimeModal.tsx
  src/components/profile/ProfileBox.tsx
  src/components/profile/ProfileKeywords.tsx
  src/components/signup/DivisionGroup.tsx
  src/components/signup/KeywordGroup.tsx
  src/components/totalBabpool/FilterModal.tsx
  src/components/totalBabpool/PageNation.tsx
  src/interface/api/authType.ts
  src/interface/api/commonType.ts
  src/interface/api/profileDetailsType.ts
  src/interface/api/profileType.ts
  src/main.tsx
  src/pages/Notification/RejectPage.styles.tsx
  src/pages/Notification/RejectPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/kakaoAuthentication/index.tsx
  src/pages/mypage/ModifyProfileCardPage.styles.tsx
  src/pages/mypage/ModifyProfileCardPage.tsx
  src/pages/mypage/Mypage.styles.tsx
  src/pages/mypage/Mypage.tsx
  src/pages/profileDetails/ProfileDetailsPage.tsx
  src/pages/receivedReview/ReceivedReviewPage.tsx
  src/pages/signup/SignUpPage.tsx
  src/pages/totalBabpool/TotalBabpoolPage.tsx
  src/provider/QueryProvider.tsx
  src/routes/index.tsx
  src/utils/util.ts
  yarn.lock
Labels: 💻 FrontEnd

#42 fix: Resolve issue with storing access token
  src/pages/kakaoAuthentication/index.tsx
Labels: 🚨 Bug, 💻 FrontEnd

#43 fix: Resolve issue with storing access token
  src/api/auth/auth.ts
  src/pages/kakaoAuthentication/index.tsx
Labels: 🚨 Bug, 💻 FrontEnd

#45 엑세스토큰 재발급, 프로필 상세조회 데이터바인딩
  src/api/api.ts
  src/api/auth/auth.ts
  src/atom/searchInfoStore.ts
  src/components/common/popup/index.tsx
  src/components/totalBabpool/FilterModal.tsx
  src/components/totalBabpool/Searchbar.tsx
  src/interface/api/profileDetailsType.ts
  src/interface/api/profileType.ts
  src/main.tsx
  src/pages/home/HomePage.tsx
  src/pages/profileDetails/ProfileDetailsPage.tsx
  src/pages/totalBabpool/TotalBabpoolPage.tsx
  src/routes/index.tsx
  src/utils/constant.ts
  src/utils/util.ts
Labels: 🛠 Feature, 💻 FrontEnd

#48 프로필 상세조회 화면, 밥약 요청 기능
  src/api/api.ts
  src/api/babRequest/babRequestApi.ts
  src/assets/gif/loading.gif
  src/components/babpoolRequest/SelectScheduleModal.tsx
  src/components/babpoolRequest/SelectTimeBox.tsx
  src/components/common/calendar/ScheduleCalendar.tsx
  src/components/common/loading/Loading.tsx
  src/interface/api/babRequestType.ts
  src/pages/babRequest/BabRequestPage.tsx
  src/pages/profileDetails/ProfileDetailsPage.tsx
  src/pages/totalBabpool/TotalBabpoolPage.tsx
  src/routes/index.tsx
  src/utils/constant.ts
  src/utils/util.ts
Labels: 🛠 Feature, 💻 FrontEnd

#59 배너링크연결, 회원탈퇴 기능
  src/api/auth/auth.ts
  src/api/profile/profileApi.ts
  src/components/explanation/C_FourthSection.tsx
  src/components/home/HomeMenu.tsx
  src/components/home/HomeSection.tsx
  src/hooks/useNavigation.ts
  src/pages/deleteAccount/DeleteAccountPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/totalBabpool/TotalBabpoolPage.tsx
  src/provider/AuthRoute.tsx
  src/routes/index.tsx
  src/utils/validate.ts
Labels: 🛠 Feature, 💻 FrontEnd

#71 QA 테스트 이슈사항
  .github/workflows/front-actions-flow.yaml
  src/components/home/HomeSection.tsx
  src/components/totalBabpool/FilterModal.tsx
  src/components/totalBabpool/PageNation.tsx
  src/hooks/useNavigation.ts
  src/pages/explanation/ExplanationPage.tsx
  src/pages/notification/accept/AcceptPage.styles.tsx
  src/pages/notification/accept/AcceptPage.tsx
  src/pages/notification/detail/NotificationDetailPage.styles.tsx
  src/pages/notification/detail/NotificationDetailPage.tsx
  src/pages/notification/reject/RejectPage.styles.tsx
  src/pages/notification/reject/RejectPage.tsx
  src/pages/profileDetails/ProfileDetailsPage.tsx
  src/pages/totalBabpool/TotalBabpoolPage.tsx
Labels: 🚨 Bug, 🛠 Feature, 💻 FrontEnd

#93 Fix/QAfix
  src/pages/mypage/modifyProfile/ModifyProfileCardPage.tsx
Labels: 🚨 Bug, 💻 FrontEnd
